name: 'Infrastructure with Terraform - Azure CI'

on:
  push:
    paths:
      - '.iac/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - '.iac/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .iac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        run: terraform plan"
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_VAR_grafana_api_token: ${{ secrets.GRAFANA_API_TOKEN }}
